services:
  postgres-service:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration-service:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      postgres-service:
        condition: service_healthy
    volumes:
      - staticfiles:/app/staticfiles
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput"

  backend-service:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      postgres-service:
        condition: service_healthy
      migration-service:
        condition: service_completed_successfully
    volumes:
      - staticfiles:/app/staticfiles
    command: gunicorn lab1.wsgi:application --bind 0.0.0.0:8000
    ports:
     - "8000:8000"

  nginx-service:
    build:
      context: ./nginx
    depends_on:
      backend-service:
        condition: service_started
      migration-service:
        condition: service_completed_successfully
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - source: nginx_selfsigned_cert
        target: /etc/nginx/certs/localhost.crt
      - source: nginx_selfsigned_key
        target: /etc/nginx/certs/localhost.key
    volumes:
      - staticfiles:/staticfiles:ro

volumes:
  postgres_data:
  staticfiles:

secrets:
  nginx_selfsigned_cert:
    file: ./secrets/localhost.crt
  nginx_selfsigned_key:
    file: ./secrets/localhost.key
